# Generated by Django 4.1.7 on 2023-03-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Emission", "0002_emission_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limit", models.IntegerField(null=True)),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="emission",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Emission.target",
            ),
        ),
    ]
