# Generated by Django 4.1.7 on 2023-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emission", "0003_target_emission_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="enery_consumption",
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="food_consumption",
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="total",
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="transportation",
            field=models.IntegerField(max_length=150, null=True),
        ),
    ]
