# Generated by Django 4.1.7 on 2023-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emission", "0004_alter_emission_enery_consumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="enery_consumption",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="food_consumption",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emission", name="total", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="transportation",
            field=models.IntegerField(null=True),
        ),
    ]
