# Generated by Django 4.1.7 on 2023-03-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emission", "0005_alter_emission_enery_consumption_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="emission", name="enery_consumption",),
        migrations.RemoveField(model_name="emission", name="food_consumption",),
        migrations.AddField(
            model_name="emission",
            name="eneryConsumption",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="emission",
            name="foodConsumption",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="total",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="transportation",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
