# Generated by Django 4.1.7 on 2023-03-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Emission", "0006_remove_emission_enery_consumption_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emission",
            old_name="eneryConsumption",
            new_name="energyConsumption",
        ),
    ]
