# Generated by Django 4.1.7 on 2023-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emission", "0007_rename_eneryconsumption_emission_energyconsumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emission",
            name="energyConsumption",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="foodConsumption",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emission", name="total", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="emission",
            name="transportation",
            field=models.IntegerField(null=True),
        ),
    ]
