# Generated by Django 4.1.7 on 2023-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
