# Generated by Django 4.1.7 on 2023-03-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="staff", new_name="is_staff",
        ),
    ]
