# Generated by Django 4.1.7 on 2023-03-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_rename_staff_user_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, null=True)),
                ("email", models.CharField(max_length=150, null=True, unique=True)),
                ("password", models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
